### ISSUE TITLE
Accept multiple files in command line

### ISSUE THREAD

**Issue by RustemA** [hi5/F4MiniMenu#14]
Hope this is the right place to ask. Can it do this? For example, start Meld with `meld file1 file2`.

**Comment by hi5** [comment]
No not at the moment. Could add it as a new method, currently we have

1. normal
2. drag & drop
3. filelist

so the :new: one could be

4. cmdline (file1 file2 file3 etc)

I actually can think of a use for this myself already so I will look into it.

At the moment for file comparison: it can be done using WinMerge as that supports Drag & Drop - [see Wiki](https://github.com/hi5/F4MiniMenu/wiki) - or you can do it in Total Commander - see here for three solutions http://superuser.com/questions/238039/can-i-use-an-replace-internal-diff-in-total-commander-with-an-external-diff-prog

If you really want to use F4MM you could do it with a little AutoHotkey helper script. Save this as meld.ahk and use that script as **Editor** and choose the **Filelist** option. That way the selected files will be put on the command line after **run**ning meld.exe (you may have to adjust the path to your meld.exe) - it will lack the icon in the popup menu of course. 

```autohotkey
FileRead, in, %1%
Loop, parse, in, `n, `r
    files .= """" A_LoopField """" A_Space
Run, c:\Program Files (x86)\Meld\Meld.exe %files%
```

**Comment by nameanyone** [comment]
Thanks for a detailed answer. I'll check the workarounds that let me use Meld, it's my tool of choice. "cmdline" totally makes sense, thanks for working on it. 👍

**Comment by hi5** [comment]
Nice project for the holidays ☃️

**Comment by hi5** [comment]
This has been added, you can try it here https://github.com/hi5/F4MiniMenu/tree/dev-method4cmdline 

When setting up an editor choose "4 - cmdline" - see also the changelog in the readme for more updates
