### ISSUE TITLE
F4MiniMenu exit automatically at first start-up if enable "Start Total Commander if not running" feature

### ISSUE THREAD

**Issue by mkitby** [hi5/F4MiniMenu#23]
Hello,

OS Env: Windows 10 64 bit

Reproduce steps:
1. Configure F4MiniMenu : 
   
    Total Commander:
         2 - Start TC if not Running(set TC Path) and TC path is set correctly
         Enable "Close F4MM when all copies of TC close"
         Enable "Close F4MM when TC closes started by F4MM"

    Filtered mode(menu): F4

2. Configure Total Commander: set F4 to run F4MiniMenu-64.exe
3. Close F4MiniMenu and Total Commander
4. Run F4MiniMenu

Expected Result:
4. F4MiniMenu is running and Total Commander is running, F4 menu in Total Commander works

Actual Result:
4. F4MiniMenu is not running, but Total Commander is running. F4 menu in Total Commander is not working when pressing F4 at first time

**Comment by mkitby** [comment]
Another finding, if disable "Close F4MM when all copies of TC close" and "Close F4MM when TC closes started by F4MM" and keep other settings. The result will be,

F4MiniMenu is running, and Total Commander is running. But F4 menu in Total Commander is not working when pressing F4 at first time

**Comment by hi5** [comment]
Good find, I'll have a look.

**Comment by hi5** [comment]
This should be fixed in v1.00
