### ISSUE TITLE
%windir%

### ISSUE THREAD

**Issue by wincmd64** [hi5/F4MiniMenu#25]
%windir% not supported?

also, double-click should call "modify"

**Comment by hi5** [comment]
> %windir% not supported?

Correct. Windows environment variables and other AutoHotkey path variables are not yet supported, but wouldn't too hard to add, so I'll add it to my todo list.

> also, double-click should call "modify"

That is already done and will be part of the next update

**Comment by hi5** [comment]
This has been added in v1.1 
* double click in editors to modify
* Path variabales https://github.com/hi5/F4MiniMenu#path-variables
