### ISSUE TITLE
Not able to run: error with the XML settings file.

### ISSUE THREAD

**Issue by qqquan** [hi5/F4MiniMenu#4]
Followed the installation instruction to unpack and run the script, and always had the following error:
---------------------------
F4MiniMenu
---------------------------
There seems to be an error with the XML settings file.
F4MiniMenu will try to create default configuration and restart.
Be sure to check the last backup of your settings in "F4MiniMenu.xml.bak"
Be sure to exit F4MiniMenu before trying to restore any backup settings.
---------------------------
OK   
---------------------------

**Comment by hi5** [comment]
@qqquan Thanks for reporting it. Although there is an error message if you click(ed) OK it would be OK at next start up. But I fixed it in v0.81, so you can try [downloading](https://github.com/hi5/F4MiniMenu) it again and you should no longer get the error message at the very first startup.

**Comment by qqquan** [comment]
Thank you for the quick response and the great script!

**Comment by hi5** [comment]
Glad to hear you find it useful.
